CREATE TABLE ideas
(
    id    BIGSERIAL PRIMARY KEY,
    label TEXT NOT NULL
        CONSTRAINT _UNIQUE_IDEA UNIQUE
);

CREATE TABLE idea_refs
(
    id            BIGSERIAL PRIMARY KEY,
    document_id   BIGINT NOT NULL,
    document_page BIGINT,
    idea_ref      BIGINT NOT NULL,
    idea_ref_text TEXT    NOT NULL,
    FOREIGN KEY (document_id) REFERENCES documents (id),
    FOREIGN KEY (idea_ref) REFERENCES ideas (id)
);