[package]
name = "ogn-db"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { git = "https://github.com/diesel-rs/diesel.git", features = ["postgres", "serde_json"] }
diesel-derive-newtype = "2.0.0-rc.0"
dotenv = "0.15.0"
serde_json = "1.0.82"
