name: CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  test:
    env:
      CI: "github" 
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "nightly"
        os:
          - ubuntu-latest
        arch:
          - x64
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: organic_notebook
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./OgnBackend
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
        with:
          project: ./OgnBackend
      - uses: julia-actions/julia-runtest@latest
        with:
          project: ./OgnBackend
        env:
          JULIA_NUM_THREADS: 4
          DB_PASSWORD: postgres
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: ./OgnBackend/src
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
