

name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.6'
      - uses: actions-rs/toolchain@v1.0.6
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: run
          toolchain: nightly
      - run: nim c -r ogn-test/main.nim
