[package]
name = "autoservice"
version = "0.1.0"
authors = ["balenamiaa <barena.ekusuimii@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
autoservice-codegen = { path = "../autoservice-codegen" }
syn = "1.0.98"
proc-macro2 = "1.0.40"
